"""
Generate AVIF and WebP variants for every product image, at the widths the
page actually renders them at.

Why this and not next/image: hosting moves to the client's own account
(proposal 2.5), and next/image's default loader is a Vercel runtime service.
A <picture> element with pre-built files is the same saving, works on any
host, costs nothing per request, and cannot break at runtime. The browser
picks the first format it understands and the smallest width it needs; the
original jpg/png stays as the last fallback, so an old browser still gets an
image.

Run from the repo root:  python scripts/build-images.py
Then commit both the generated files and content/images.generated.ts.
"""
import json, pathlib, sys
import pillow_avif  # noqa: F401  registers the AVIF encoder with Pillow
from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parent.parent
PUB = ROOT / "web" / "public"

# Widths are taken from the rendered layout, not invented. A file is never
# upscaled: a width above the source's own is dropped.
SOURCES = {
    # Full-bleed map. Largest CSS box is the 1400px wide container; 2x of that
    # is beyond the capture, so the source width is the ceiling.
    "product/map-2x.jpg": [640, 960, 1440, 1920, 2320],
    # Record card, right column of a two-up. ~640 CSS px at the widest.
    "product/home-record.jpg": [640, 960, 1280, 1681],
    "product/home-record-tall.jpg": [400, 692],
    # The founders, on the about page. Beside the copy at about 420 CSS px on a
    # wide screen and full width on a phone, so 840 is the 2x it needs and the
    # source's own 1237 is the ceiling.
    "about/founders.jpg": [420, 840, 1237],
    # Phone captures. The CSS caps them near 368 CSS px, so 760 is already 2x.
    "product/phone-assessment.png": [380, 760],
    "product/phone-route.png": [380, 760],
    "product/phone-visit-form.png": [380, 760],
}

QUALITY = {"avif": 52, "webp": 78}

# Per-image override, for images where the quality simply does not have to be
# there. The hero map is the whole first viewport by area, so it is the single
# heaviest thing on the critical path, and it is also aria-hidden decoration
# sitting behind the headline: nobody reads it, and no claim rests on it. The
# record card and the phone captures are the opposite, text in a screenshot
# that somebody will squint at, so they keep the default.
QUALITY_BY_SOURCE = {
    "product/map-2x.jpg": {"avif": 38, "webp": 66},
}


def build():
    manifest = {}
    total_before = total_after = 0
    for rel, widths in SOURCES.items():
        src = PUB / rel
        if not src.exists():
            sys.exit(f"missing source: {src}")
        im = Image.open(src)
        stem = src.with_suffix("")
        total_before += src.stat().st_size
        entry = {"width": im.width, "height": im.height, "avif": [], "webp": []}

        quality = {**QUALITY, **QUALITY_BY_SOURCE.get(rel, {})}

        for w in sorted({min(w, im.width) for w in widths}):
            resized = im if w == im.width else im.resize(
                (w, round(im.height * w / im.width)), Image.LANCZOS
            )
            for fmt in ("avif", "webp"):
                out = stem.parent / f"{stem.name}-{w}.{fmt}"
                # AVIF has no palette mode and WebP wants straight RGB(A).
                frame = resized.convert("RGBA" if "A" in resized.mode else "RGB")
                frame.save(out, quality=quality[fmt], method=6 if fmt == "webp" else None)
                total_after += out.stat().st_size
                entry[fmt].append([w, "/" + out.relative_to(PUB).as_posix()])
        manifest["/" + rel] = entry
        print(f"{rel}: {len(entry['avif'])} widths")

    ts = ROOT / "web" / "content" / "images.generated.ts"
    ts.write_text(
        "/* GENERATED by scripts/build-images.py. Do not edit by hand.\n"
        " * Regenerate after replacing any file in web/public/product. */\n\n"
        "export type Variant = [width: number, src: string];\n"
        "export type Entry = { width: number; height: number; avif: Variant[]; webp: Variant[] };\n\n"
        "export const images: Record<string, Entry> = " + json.dumps(manifest, indent=2) + ";\n",
        encoding="utf-8",
    )
    print(f"\noriginals {total_before/1024:.0f} KB -> variants {total_after/1024:.0f} KB")


if __name__ == "__main__":
    build()
