"""
Bundle the design system tokens into one stylesheet.

The tokens live in nine files because that is how they are edited. The browser
should not pay for that: ds/styles.css @imports them, so the browser fetched
styles.css, parsed it, then fetched nine more files, and one of those
(fonts.css) @imported the Google Fonts stylesheet, which then requested the
font binaries. Four serial round trips before a single character could paint.

This flattens the nine into ds/tokens.css. The Google Fonts request is lifted
out entirely and goes in the document <head> as a plain <link>, next to a
preconnect, so it starts at the same moment as everything else.

Edit the files in ds/tokens/. Then run:  python scripts/build-ds.py
"""
import pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DS = ROOT / "web" / "public" / "ds"
ENTRY = DS / "styles.css"
OUT = DS / "tokens.css"

order = re.findall(r'@import\s+url\("([^"]+)"\)', ENTRY.read_text(encoding="utf-8"))
if not order:
    sys.exit(f"no @import list found in {ENTRY}")

parts = [
    "/* GENERATED by scripts/build-ds.py from ds/styles.css and ds/tokens/.\n"
    " * Do not edit. Edit the token files and re-run the script.\n"
    " * The webfont request is NOT here: it is a <link> in the document head,\n"
    " * so it does not wait for this file to be parsed first. */\n"
]
for rel in order:
    f = (DS / rel).resolve()
    text = f.read_text(encoding="utf-8")
    # Remote @import inside a stylesheet is exactly the serial hop being
    # removed. Anything left pointing outward is a mistake, so say so.
    remote = re.findall(r'@import\s+url\("(https?:[^"]+)"\)', text)
    for url in remote:
        print(f"  lifted out of {rel}: {url}")
    text = re.sub(r'@import\s+url\("https?:[^"]+"\);\s*', "", text)
    parts.append(f"\n/* ---- {rel} ---- */\n{text.strip()}\n")

OUT.write_text("".join(parts), encoding="utf-8")
print(f"\n{OUT.relative_to(ROOT)}  {OUT.stat().st_size / 1024:.1f} KB from {len(order)} files")
