/* GENERATED by scripts/build-images.py. Do not edit by hand.
 * Regenerate after replacing any file in web/public/product. */

export type Variant = [width: number, src: string];
export type Entry = { width: number; height: number; avif: Variant[]; webp: Variant[] };

export const images: Record<string, Entry> = {
  "/product/map-2x.jpg": {
    "width": 2320,
    "height": 1290,
    "avif": [
      [
        640,
        "/product/map-2x-640.avif"
      ],
      [
        960,
        "/product/map-2x-960.avif"
      ],
      [
        1440,
        "/product/map-2x-1440.avif"
      ],
      [
        1920,
        "/product/map-2x-1920.avif"
      ],
      [
        2320,
        "/product/map-2x-2320.avif"
      ]
    ],
    "webp": [
      [
        640,
        "/product/map-2x-640.webp"
      ],
      [
        960,
        "/product/map-2x-960.webp"
      ],
      [
        1440,
        "/product/map-2x-1440.webp"
      ],
      [
        1920,
        "/product/map-2x-1920.webp"
      ],
      [
        2320,
        "/product/map-2x-2320.webp"
      ]
    ]
  },
  "/product/home-record.jpg": {
    "width": 1681,
    "height": 936,
    "avif": [
      [
        640,
        "/product/home-record-640.avif"
      ],
      [
        960,
        "/product/home-record-960.avif"
      ],
      [
        1280,
        "/product/home-record-1280.avif"
      ],
      [
        1681,
        "/product/home-record-1681.avif"
      ]
    ],
    "webp": [
      [
        640,
        "/product/home-record-640.webp"
      ],
      [
        960,
        "/product/home-record-960.webp"
      ],
      [
        1280,
        "/product/home-record-1280.webp"
      ],
      [
        1681,
        "/product/home-record-1681.webp"
      ]
    ]
  },
  "/product/home-record-tall.jpg": {
    "width": 692,
    "height": 519,
    "avif": [
      [
        400,
        "/product/home-record-tall-400.avif"
      ],
      [
        692,
        "/product/home-record-tall-692.avif"
      ]
    ],
    "webp": [
      [
        400,
        "/product/home-record-tall-400.webp"
      ],
      [
        692,
        "/product/home-record-tall-692.webp"
      ]
    ]
  },
  "/product/phone-assessment.png": {
    "width": 760,
    "height": 1540,
    "avif": [
      [
        380,
        "/product/phone-assessment-380.avif"
      ],
      [
        760,
        "/product/phone-assessment-760.avif"
      ]
    ],
    "webp": [
      [
        380,
        "/product/phone-assessment-380.webp"
      ],
      [
        760,
        "/product/phone-assessment-760.webp"
      ]
    ]
  },
  "/product/phone-route.png": {
    "width": 760,
    "height": 1544,
    "avif": [
      [
        380,
        "/product/phone-route-380.avif"
      ],
      [
        760,
        "/product/phone-route-760.avif"
      ]
    ],
    "webp": [
      [
        380,
        "/product/phone-route-380.webp"
      ],
      [
        760,
        "/product/phone-route-760.webp"
      ]
    ]
  },
  "/product/phone-visit-form.png": {
    "width": 760,
    "height": 1544,
    "avif": [
      [
        380,
        "/product/phone-visit-form-380.avif"
      ],
      [
        760,
        "/product/phone-visit-form-760.avif"
      ]
    ],
    "webp": [
      [
        380,
        "/product/phone-visit-form-380.webp"
      ],
      [
        760,
        "/product/phone-visit-form-760.webp"
      ]
    ]
  }
};
